import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, onAuthStateChanged, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { getFirestore, doc, setDoc, getDoc, collection, addDoc, getDocs, query, where, orderBy, serverTimestamp, updateDoc } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import { getStorage, ref, uploadBytesResumable, getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-storage.js';
import { firebaseConfig, whatsappNumber } from './firebase-config.js';
const missing=Object.values(firebaseConfig).some(v=>!v||String(v).includes('YOUR_'));
let app,auth,db,storage;
if(!missing){const {getApp}=await import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js');app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);storage=getStorage(app)}
const $=s=>document.querySelector(s);const toast=m=>{const el=$('#toast')||$('#notice');if(!el)return;el.textContent=m;el.hidden=false;el.classList.add('show');setTimeout(()=>{el.classList.remove('show');if(el.id==='notice')el.hidden=true},3200)};
function configNotice(){if(missing){let n=$('#notice');if(n){n.hidden=false;n.textContent='الواجهة جاهزة، لكن تسجيل الدخول يحتاج إعداد بيانات Firebase في firebase-config.js.'}let host=$('.student-main')||$('.admin-main');if(host&&!host.querySelector('.setup-warning'))host.insertAdjacentHTML('afterbegin',`<div class="setup-warning">اربط بيانات Firebase في firebase-config.js لتفعيل الحسابات والبيانات الحقيقية.</div>`)}}
configNotice();
if($('#loginForm')){
 const forms={login:$('#loginForm'),register:$('#registerForm')};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));Object.entries(forms).forEach(([k,f])=>f.hidden=k!==b.dataset.tab);$('#notice').hidden=true});
 forms.login.onsubmit=async e=>{e.preventDefault();if(missing)return configNotice();let d=new FormData(e.currentTarget);try{await signInWithEmailAndPassword(auth,d.get('email'),d.get('password'));}catch(err){toast(authMessage(err))}};
 forms.register.onsubmit=async e=>{e.preventDefault();if(missing)return configNotice();let d=new FormData(e.currentTarget);try{let cred=await createUserWithEmailAndPassword(auth,d.get('email'),d.get('password'));await updateProfile(cred.user,{displayName:d.get('name')});await setDoc(doc(db,'users',cred.user.uid),{name:d.get('name'),email:d.get('email'),phone:d.get('phone'),grade:d.get('grade'),role:'student',subscription:{status:'pending'},createdAt:serverTimestamp()});}catch(err){toast(authMessage(err))}};
 if(auth)onAuthStateChanged(auth,async u=>{if(!u)return;let snap=await getDoc(doc(db,'users',u.uid));if(snap.exists())location.replace(snap.data().role==='admin'?'admin.html':'student.html')});configNotice();
}
function authMessage(e){return ({'auth/email-already-in-use':'الإيميل مستخدم بالفعل.','auth/invalid-credential':'الإيميل أو كلمة المرور غير صحيحة.','auth/weak-password':'كلمة المرور لازم تكون 6 أحرف على الأقل.','auth/invalid-email':'اكتب بريد إلكتروني صحيح.','auth/too-many-requests':'محاولات كتير، جرّب بعد شوية.'})[e.code]||'حصلت مشكلة. راجع البيانات وحاول تاني.'}
if($('#studentName')&&auth)onAuthStateChanged(auth,async u=>{const showProblem=message=>{const box=document.createElement('div');box.className='setup-warning';box.textContent=message+' ';const link=document.createElement('a');link.href='index.html';link.textContent='العودة لتسجيل الدخول';box.append(link);$('.student-main').prepend(box)};if(!u){showProblem('جلسة الدخول غير موجودة على هذه الصفحة.');return}try{let s=await getDoc(doc(db,'users',u.uid));if(!s.exists()){showProblem('تم تسجيل الدخول، لكن ملف الطالب غير موجود في قاعدة البيانات.');return}let profile=s.data();if(profile.role!=='student'){showProblem('الحساب الحالي ليس مسجلًا بدور طالب.');return}$('#studentName').textContent=profile.name||u.displayName||'الطالب';$('#subscriptionStatus').textContent=subscriptionText(profile.subscription);$('#whatsappLink').href=`https://wa.me/${whatsappNumber}?text=${encodeURIComponent('السلام عليكم، أنا '+(profile.name||'طالب')+' وعايز أستفسر عن الاشتراك.')}`;await loadStudentContent(profile)}catch(error){console.error('Student page load failed:',error);showProblem('تعذر تحميل بيانات الطالب. تأكد من اتصال الإنترنت وصلاحيات Firestore، ثم أرسل صورة هذه الرسالة.')}});
function subscriptionText(s){if(!s||s.status==='pending')return 'حسابك في انتظار تفعيل الاشتراك. تواصل مع الأستاذ عبر واتساب.';if(s.status==='active')return `اشتراكك نشط${s.endsAt?' حتى '+s.endsAt:''}. بالتوفيق في التعلم!`;return 'اشتراكك غير نشط حاليًا. تواصل مع الأستاذ للتجديد.'}
async function loadStudentContent(p){const [ls,as,es]=await Promise.all([getDocs(collection(db,'lessons')),getDocs(collection(db,'assignments')),getDocs(collection(db,'exams'))]);const fits=x=>x.grade==='all'||x.grade===p.grade;$('#lessonList').innerHTML=ls.docs.map(d=>({id:d.id,...d.data()})).filter(fits).map(x=>`<article class="content-card"><div class="content-thumb">▶</div><div class="content-card-body"><span class="card-tag">${escapeHtml(x.grade==='all'?'كل المراحل':x.grade||'درس برمجة')}</span><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description||'درس شرح من المنصة')}</p><a class="btn primary" href="${x.videoUrl}" target="_blank" rel="noreferrer">مشاهدة الدرس ↗</a></div></article>`).join('')||empty('لسه مفيش دروس منشورة.');$('#assignmentList').innerHTML=as.docs.map(d=>({id:d.id,...d.data()})).filter(x=>fits(x)&&x.active!==false).map(x=>`<article class="task-card"><div class="task-icon">✎</div><div class="task-content"><span class="card-tag">${escapeHtml(x.grade==='all'?'كل المراحل':x.grade||'واجب')}</span><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description||'ابعث إجابتك للأستاذ للمراجعة.')}</p><form class="submit-form" data-assignment="${x.id}"><textarea name="answer" rows="3" required placeholder="اكتب إجابتك هنا..."></textarea><button class="btn primary" type="submit">إرسال الواجب</button></form></div></article>`).join('')||empty('مفيش واجبات متاحة دلوقتي.');$('#examList').innerHTML=es.docs.map(d=>({id:d.id,...d.data()})).filter(x=>fits(x)&&x.active!==false).map(x=>`<article class="task-card"><div class="task-icon exam">✓</div><div class="task-content"><span class="card-tag">${escapeHtml(x.grade==='all'?'كل المراحل':x.grade||'امتحان')}</span><h3>${escapeHtml(x.title)}</h3><p>${(x.questions||[]).length} أسئلة · ابعت إجاباتك للأستاذ.</p><button class="btn primary" data-exam="${x.id}">ابدأ الامتحان</button></div></article>`).join('')||empty('مفيش امتحانات متاحة دلوقتي.');bindStudent(p)}
function bindStudent(p){document.querySelectorAll('[data-assignment]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();let formData=new FormData(f),answer=formData.get('answer'),file=formData.get('attachment'),attachmentUrl='';if(file&&file.size){if(file.size>20*1024*1024){toast('حجم الملف لازم يكون أقل من 20 ميجابايت');return}const task=uploadBytesResumable(ref(storage,'homework/'+auth.currentUser.uid+'/'+Date.now()+'-'+file.name),file);await new Promise((resolve,reject)=>task.on('state_changed',()=>{},reject,resolve));attachmentUrl=await getDownloadURL(task.snapshot.ref)}let assignment=await getDoc(doc(db,'assignments',f.dataset.assignment));await addDoc(collection(db,'submissions'),{assignmentId:f.dataset.assignment,assignmentTitle:assignment.exists()?assignment.data().title:'واجب',studentId:auth.currentUser.uid,studentName:p.name,studentEmail:p.email,grade:p.grade,answer,attachmentUrl,status:'new',createdAt:serverTimestamp()});f.reset();toast('تم إرسال الواجب للأستاذ.')});document.querySelectorAll('[data-exam]').forEach(b=>b.onclick=async()=>{let s=await getDoc(doc(db,'exams',b.dataset.exam));if(!s.exists())return;let ex=s.data();let questions=ex.questions||[];let html=`<h2>${escapeHtml(ex.title)}</h2><form id="takeExam">${questions.map((q,i)=>`<fieldset class="question"><legend>${i+1}. ${escapeHtml(q.text)}</legend>${q.options.map(o=>`<label class="choice"><input type="radio" name="q${i}" value="${escapeHtml(o)}" required>${escapeHtml(o)}</label>`).join('')}</fieldset>`).join('')}<button class="btn primary" type="submit">إرسال الإجابات</button></form>`;$('#modalContent').innerHTML=html;$('#modal').hidden=false;$('#takeExam').onsubmit=async e=>{e.preventDefault();let answers=Object.fromEntries(new FormData(e.currentTarget));await addDoc(collection(db,'examSubmissions'),{examId:b.dataset.exam,examTitle:ex.title,studentId:auth.currentUser.uid,studentName:p.name,grade:p.grade,answers,status:'new',createdAt:serverTimestamp()});$('#modal').hidden=true;toast('تم إرسال إجاباتك للأستاذ.')}})}
if($('#logoutBtn')&&auth)$('#logoutBtn').onclick=()=>signOut(auth);
if($('#closeModal'))$('#closeModal').onclick=()=>$('#modal').hidden=true;
if($('#admin-bogus'))console.log('');
if($('#submissionsList')&&auth)onAuthStateChanged(auth,async u=>{if(!u){location.replace('index.html');return}let s=await getDoc(doc(db,'users',u.uid));if(!s.exists()||s.data().role!=='admin'){await signOut(auth);location.replace('index.html');return}await loadAdmin()});
async function loadAdmin(){let [subs,lessons,users,examSubs]=await Promise.all([getDocs(collection(db,'submissions')),getDocs(collection(db,'lessons')),getDocs(collection(db,'users')),getDocs(collection(db,'examSubmissions'))]);$('#pendingCount').textContent=subs.docs.filter(x=>x.data().status==='new').length;$('#examSubmissionsList').innerHTML=examSubs.docs.map(d=>({id:d.id,...d.data()})).map(x=>`<article class="submission-row"><div><span class="card-tag">${escapeHtml(x.grade||'طالب')} · ${escapeHtml(x.studentName||'')}</span><h3>${escapeHtml(x.examTitle||'امتحان')}</h3><p>${escapeHtml(JSON.stringify(x.answers||{}))}</p></div><span class="status-pill ${x.status==='new'?'pending':''}">${x.status==='new'?'بانتظار المراجعة':'تمت المراجعة'}</span></article>`).join('')||empty('لا توجد إجابات امتحانات بعد.');$('#lessonCount').textContent=lessons.size;$('#studentCount').textContent=users.docs.filter(x=>x.data().role==='student').length;$('#submissionsList').innerHTML=subs.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(x=>`<article class="submission-row"><div><span class="card-tag">${escapeHtml(x.grade||'طالب')} · ${escapeHtml(x.studentEmail||'')}</span><h3>${escapeHtml(x.assignmentTitle||'واجب مرسل')}</h3><p>${escapeHtml(x.answer||'')}</p>${x.attachmentUrl?`<a class="text-file" href="${x.attachmentUrl}" target="_blank" rel="noreferrer">فتح المرفق ↗</a>`:''}</div><div class="submission-actions"><span class="status-pill ${x.status==='new'?'pending':''}">${x.status==='new'?'جديد':'تمت المراجعة'}</span><button class="btn small-btn" data-reviewed="${x.id}">تمت المراجعة</button></div></article>`).join('')||empty('مفيش واجبات مرسلة لحد دلوقتي.');document.querySelectorAll('[data-reviewed]').forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,'submissions',b.dataset.reviewed),{status:'reviewed'});loadAdmin()});$('#studentsList').innerHTML=users.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.role==='student').map(x=>`<article class="student-row"><div><b>${escapeHtml(x.name||'طالب')}</b><small>${escapeHtml(x.email||'')} · ${escapeHtml(x.grade||'')}</small></div><select data-subscription="${x.id}"><option value="pending" ${x.subscription?.status==='pending'?'selected':''}>بانتظار التفعيل</option><option value="active" ${x.subscription?.status==='active'?'selected':''}>نشط</option><option value="inactive" ${x.subscription?.status==='inactive'?'selected':''}>غير نشط</option></select></article>`).join('')||empty('لا يوجد طلاب مسجلون بعد.');document.querySelectorAll('[data-subscription]').forEach(sel=>sel.onchange=async()=>{await updateDoc(doc(db,'users',sel.dataset.subscription),{subscription:{status:sel.value,updatedAt:new Date().toISOString().slice(0,10)}});toast('تم تحديث حالة الاشتراك')});bindAdmin()}
function bindAdmin(){$('#assignmentForm').onsubmit=async e=>{e.preventDefault();let f=e.currentTarget,d=new FormData(f);await addDoc(collection(db,'assignments'),{title:d.get('title'),description:d.get('description'),grade:d.get('grade'),active:true,createdAt:serverTimestamp()});f.reset();toast('تم نشر الواجب للطلاب');loadAdmin()};$('#lessonForm').onsubmit=async e=>{e.preventDefault();let f=e.currentTarget,d=new FormData(f),file=d.get('video');let task=uploadBytesResumable(ref(storage,`lessons/${Date.now()}-${file.name}`),file);task.on('state_changed',s=>toast(`رفع الفيديو ${Math.round(s.bytesTransferred/s.totalBytes*100)}%`),err=>toast('تعذر رفع الفيديو'),async()=>{let videoUrl=await getDownloadURL(task.snapshot.ref);await addDoc(collection(db,'lessons'),{title:d.get('title'),description:d.get('description'),grade:d.get('grade'),videoUrl,createdAt:serverTimestamp(),active:true});f.reset();toast('تم نشر الدرس');loadAdmin()})};$('#examForm').onsubmit=async e=>{e.preventDefault();let f=e.currentTarget,d=new FormData(f);let questions=String(d.get('questions')).split('\n').filter(Boolean).map(line=>{let [text,...options]=line.split('|').map(s=>s.trim());return {text,options}});await addDoc(collection(db,'exams'),{title:d.get('title'),grade:d.get('grade'),questions,active:true,createdAt:serverTimestamp()});f.reset();toast('تم نشر الامتحان للطلاب')};}
function empty(m){return `<div class="empty-state">${escapeHtml(m)}</div>`}function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}





